name: bedtwLCoreOSS
version: '${project.version}'
main: me.bedtwL.oss.CoreOSS
softdepend: ["LuckPerms"]
commands:
  world:
    aliases:
      - w
  lobby:
    aliases:
      - hub
      - l
      - quit